CREATE TABLE IF NOT EXISTS app_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_date TEXT NOT NULL,
    generated_at TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    is_current INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sales_imports (
    sales_date TEXT PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_rows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_date TEXT NOT NULL,
    store_code TEXT NOT NULL,
    store_name TEXT,
    product_code TEXT NOT NULL,
    product_name TEXT,
    sales_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    discard_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    ending_stock DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sales_rows_date ON sales_rows (sales_date);
CREATE INDEX IF NOT EXISTS idx_sales_rows_store_product ON sales_rows (store_code, product_code);
CREATE INDEX IF NOT EXISTS idx_sales_rows_store_date_product ON sales_rows (store_code, sales_date, product_code);

CREATE TABLE IF NOT EXISTS store_notes (
    store_key TEXT PRIMARY KEY,
    note TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS store_routes (
    store_key TEXT PRIMARY KEY,
    route TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS shipment_entries (
    store_key TEXT NOT NULL,
    shipment_date TEXT NOT NULL,
    product_code TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (store_key, shipment_date, product_code)
);

CREATE TABLE IF NOT EXISTS stock_adjustment_entries (
    store_key TEXT NOT NULL,
    shipment_date TEXT NOT NULL,
    product_code TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (store_key, shipment_date, product_code)
);

CREATE TABLE IF NOT EXISTS harvest_entries (
    harvest_date TEXT NOT NULL,
    sheet_name TEXT NOT NULL,
    row_index INTEGER NOT NULL,
    column_letter TEXT NOT NULL,
    product_name TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (harvest_date, sheet_name, row_index, column_letter)
);

CREATE TABLE IF NOT EXISTS harvest_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_date TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_harvest_messages_date
    ON harvest_messages (harvest_date, id);

CREATE TABLE IF NOT EXISTS field_work_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL DEFAULT '',
    net_house_code TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_field_work_messages_date
    ON field_work_messages (work_date, id);

CREATE INDEX IF NOT EXISTS idx_field_work_messages_net_house
    ON field_work_messages (zone_name, net_house_code, work_date, id);

CREATE TABLE IF NOT EXISTS field_work_message_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    original_name TEXT NOT NULL DEFAULT '',
    content_type TEXT NOT NULL DEFAULT '',
    url_path TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_field_work_message_photos_message
    ON field_work_message_photos (message_id, id);

CREATE TABLE IF NOT EXISTS field_zones (
    zone_name TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS field_net_houses (
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    grid_count DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT '',
    crop1 TEXT NOT NULL DEFAULT '',
    crop2 TEXT NOT NULL DEFAULT '',
    planted_date TEXT NOT NULL DEFAULT '',
    harvest_date TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    source_row INTEGER,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (zone_name, net_house_code),
    FOREIGN KEY (zone_name) REFERENCES field_zones(zone_name) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_field_net_houses_zone
    ON field_net_houses (zone_name, net_house_code);

CREATE TABLE IF NOT EXISTS field_work_records (
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    task_key TEXT NOT NULL,
    task_label TEXT NOT NULL,
    fertilizer_bag_count DOUBLE PRECISION,
    crop_key TEXT NOT NULL DEFAULT '',
    crop_name TEXT NOT NULL DEFAULT '',
    account_name TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL,
    PRIMARY KEY (work_date, zone_name, net_house_code, task_key)
);

CREATE INDEX IF NOT EXISTS idx_field_work_records_selection
    ON field_work_records (work_date, zone_name, net_house_code);

CREATE TABLE IF NOT EXISTS field_work_record_crops (
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    task_key TEXT NOT NULL,
    crop_index INTEGER NOT NULL,
    crop_key TEXT NOT NULL DEFAULT '',
    crop_name TEXT NOT NULL DEFAULT '',
    tray_count DOUBLE PRECISION,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (work_date, zone_name, net_house_code, task_key, crop_index)
);

CREATE INDEX IF NOT EXISTS idx_field_work_record_crops_selection
    ON field_work_record_crops (work_date, zone_name, net_house_code, task_key);

CREATE INDEX IF NOT EXISTS idx_field_work_record_crops_crop
    ON field_work_record_crops (crop_key);

CREATE TABLE IF NOT EXISTS field_bt_records (
    work_date TEXT NOT NULL,
    area_key TEXT NOT NULL,
    area_label TEXT NOT NULL,
    package_count INTEGER,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (work_date, area_key)
);

CREATE INDEX IF NOT EXISTS idx_field_bt_records_date
    ON field_bt_records (work_date, area_key);

CREATE TABLE IF NOT EXISTS net_house_status_records (
    record_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    status TEXT NOT NULL,
    crop_name TEXT NOT NULL DEFAULT '',
    planted_date TEXT NOT NULL DEFAULT '',
    harvest_date TEXT NOT NULL DEFAULT '',
    estimated_quantity DOUBLE PRECISION,
    lunch_marked INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (record_date, zone_name, net_house_code)
);

CREATE INDEX IF NOT EXISTS idx_net_house_status_records_date
    ON net_house_status_records (record_date, zone_name, net_house_code);

CREATE TABLE IF NOT EXISTS net_house_status_record_crops (
    record_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    crop_index INTEGER NOT NULL,
    crop_name TEXT NOT NULL DEFAULT '',
    harvest_date TEXT NOT NULL DEFAULT '',
    estimated_quantity DOUBLE PRECISION,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (record_date, zone_name, net_house_code, crop_index),
    FOREIGN KEY (record_date, zone_name, net_house_code)
        REFERENCES net_house_status_records(record_date, zone_name, net_house_code)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_net_house_status_record_crops_selection
    ON net_house_status_record_crops (record_date, zone_name, net_house_code);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_role
    ON users (role);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user
    ON auth_sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires
    ON auth_sessions (expires_at);
