CREATE TABLE IF NOT EXISTS field_work_record_audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    operation TEXT NOT NULL,
    account_name TEXT NOT NULL DEFAULT '',
    before_json TEXT NOT NULL,
    after_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_selection
    ON field_work_record_audit_logs (work_date, zone_name, net_house_code, id);

CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_created
    ON field_work_record_audit_logs (created_at, id);
