from __future__ import annotations

import json
import os
import re
import sqlite3
import threading
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
TAIPEI_TZ = timezone(timedelta(hours=8))


def app_path_from_env(name: str, default: Path) -> Path:
    value = os.environ.get(name)
    if not value:
        return default
    path = Path(value).expanduser()
    return path if path.is_absolute() else ROOT / path


DATA_DIR = app_path_from_env("APP_DATA_DIR", ROOT / "data")
DB_PATH = app_path_from_env("APP_DB_PATH", DATA_DIR / "app.db")
DATABASE_BACKEND = os.environ.get("DATABASE_BACKEND") or ("postgres" if os.environ.get("DATABASE_URL") else "sqlite")
DATABASE_URL = os.environ.get("DATABASE_URL", "")
POSTGRES_SCHEMA_LOCK_ID = 2026052201
_POSTGRES_SCHEMA_INIT_LOCK = threading.Lock()
_POSTGRES_SCHEMA_INITIALIZED = False


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS app_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_date TEXT NOT NULL,
    generated_at TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    is_current INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sales_imports (
    sales_date TEXT PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_rows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_date TEXT NOT NULL,
    store_code TEXT NOT NULL,
    store_name TEXT,
    product_code TEXT NOT NULL,
    product_name TEXT,
    sales_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    discard_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    ending_stock DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sales_rows_date ON sales_rows (sales_date);
CREATE INDEX IF NOT EXISTS idx_sales_rows_store_product ON sales_rows (store_code, product_code);
CREATE INDEX IF NOT EXISTS idx_sales_rows_store_date_product ON sales_rows (store_code, sales_date, product_code);

CREATE TABLE IF NOT EXISTS store_notes (
    store_key TEXT PRIMARY KEY,
    note TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS store_routes (
    store_key TEXT PRIMARY KEY,
    route TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS shipment_entries (
    store_key TEXT NOT NULL,
    shipment_date TEXT NOT NULL,
    product_code TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (store_key, shipment_date, product_code)
);

CREATE TABLE IF NOT EXISTS stock_adjustment_entries (
    store_key TEXT NOT NULL,
    shipment_date TEXT NOT NULL,
    product_code TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (store_key, shipment_date, product_code)
);

CREATE TABLE IF NOT EXISTS harvest_entries (
    harvest_date TEXT NOT NULL,
    sheet_name TEXT NOT NULL,
    row_index INTEGER NOT NULL,
    column_letter TEXT NOT NULL,
    product_name TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (harvest_date, sheet_name, row_index, column_letter)
);

CREATE TABLE IF NOT EXISTS harvest_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_date TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_harvest_messages_date
    ON harvest_messages (harvest_date, id);

CREATE TABLE IF NOT EXISTS field_work_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL DEFAULT '',
    net_house_code TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_field_work_messages_date
    ON field_work_messages (work_date, id);

CREATE INDEX IF NOT EXISTS idx_field_work_messages_net_house
    ON field_work_messages (zone_name, net_house_code, work_date, id);

CREATE TABLE IF NOT EXISTS field_work_message_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    original_name TEXT NOT NULL DEFAULT '',
    content_type TEXT NOT NULL DEFAULT '',
    url_path TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_field_work_message_photos_message
    ON field_work_message_photos (message_id, id);

CREATE TABLE IF NOT EXISTS field_zones (
    zone_name TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS field_net_houses (
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    grid_count DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT '',
    crop1 TEXT NOT NULL DEFAULT '',
    crop2 TEXT NOT NULL DEFAULT '',
    planted_date TEXT NOT NULL DEFAULT '',
    harvest_date TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    source_row INTEGER,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (zone_name, net_house_code),
    FOREIGN KEY (zone_name) REFERENCES field_zones(zone_name) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_field_net_houses_zone
    ON field_net_houses (zone_name, net_house_code);

CREATE TABLE IF NOT EXISTS field_work_records (
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    task_key TEXT NOT NULL,
    task_label TEXT NOT NULL,
    fertilizer_bag_count DOUBLE PRECISION,
    crop_key TEXT NOT NULL DEFAULT '',
    crop_name TEXT NOT NULL DEFAULT '',
    account_name TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL,
    PRIMARY KEY (work_date, zone_name, net_house_code, task_key)
);

CREATE INDEX IF NOT EXISTS idx_field_work_records_selection
    ON field_work_records (work_date, zone_name, net_house_code);

ALTER TABLE field_work_records
    ADD COLUMN IF NOT EXISTS account_name TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS field_work_record_crops (
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    task_key TEXT NOT NULL,
    crop_index INTEGER NOT NULL,
    crop_key TEXT NOT NULL DEFAULT '',
    crop_name TEXT NOT NULL DEFAULT '',
    tray_count DOUBLE PRECISION,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (work_date, zone_name, net_house_code, task_key, crop_index)
);

CREATE INDEX IF NOT EXISTS idx_field_work_record_crops_selection
    ON field_work_record_crops (work_date, zone_name, net_house_code, task_key);

CREATE INDEX IF NOT EXISTS idx_field_work_record_crops_crop
    ON field_work_record_crops (crop_key);

CREATE TABLE IF NOT EXISTS field_work_record_audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    operation TEXT NOT NULL,
    account_name TEXT NOT NULL DEFAULT '',
    before_json TEXT NOT NULL,
    after_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_selection
    ON field_work_record_audit_logs (work_date, zone_name, net_house_code, id);

CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_created
    ON field_work_record_audit_logs (created_at, id);

CREATE TABLE IF NOT EXISTS field_bt_records (
    work_date TEXT NOT NULL,
    area_key TEXT NOT NULL,
    area_label TEXT NOT NULL,
    package_count INTEGER,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (work_date, area_key)
);

CREATE INDEX IF NOT EXISTS idx_field_bt_records_date
    ON field_bt_records (work_date, area_key);

CREATE TABLE IF NOT EXISTS net_house_status_records (
    record_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    status TEXT NOT NULL,
    crop_name TEXT NOT NULL DEFAULT '',
    planted_date TEXT NOT NULL DEFAULT '',
    harvest_date TEXT NOT NULL DEFAULT '',
    estimated_quantity DOUBLE PRECISION,
    harvest_quantity DOUBLE PRECISION,
    lunch_marked INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (record_date, zone_name, net_house_code)
);

CREATE INDEX IF NOT EXISTS idx_net_house_status_records_date
    ON net_house_status_records (record_date, zone_name, net_house_code);

ALTER TABLE net_house_status_records
    ADD COLUMN IF NOT EXISTS lunch_marked INTEGER NOT NULL DEFAULT 0;

ALTER TABLE net_house_status_records
    ADD COLUMN IF NOT EXISTS harvest_quantity DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS net_house_status_record_crops (
    record_date TEXT NOT NULL,
    zone_name TEXT NOT NULL,
    net_house_code TEXT NOT NULL,
    crop_index INTEGER NOT NULL,
    crop_name TEXT NOT NULL DEFAULT '',
    harvest_date TEXT NOT NULL DEFAULT '',
    estimated_quantity DOUBLE PRECISION,
    harvest_quantity DOUBLE PRECISION,
    destroyed INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (record_date, zone_name, net_house_code, crop_index),
    FOREIGN KEY (record_date, zone_name, net_house_code)
        REFERENCES net_house_status_records(record_date, zone_name, net_house_code)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_net_house_status_record_crops_selection
    ON net_house_status_record_crops (record_date, zone_name, net_house_code);

ALTER TABLE net_house_status_record_crops
    ADD COLUMN IF NOT EXISTS destroyed INTEGER NOT NULL DEFAULT 0;

ALTER TABLE net_house_status_record_crops
    ADD COLUMN IF NOT EXISTS harvest_quantity DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS daily_vegetable_manual_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_date TEXT NOT NULL,
    crop_name TEXT NOT NULL DEFAULT '',
    net_house_code TEXT NOT NULL DEFAULT '',
    quantity DOUBLE PRECISION,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_daily_vegetable_manual_entries_date
    ON daily_vegetable_manual_entries (harvest_date, id);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_role
    ON users (role);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user
    ON auth_sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires
    ON auth_sessions (expires_at);
"""


def taipei_now() -> datetime:
    return datetime.now(TAIPEI_TZ)


def taipei_now_text() -> str:
    return taipei_now().isoformat(timespec="seconds")


def database_backend() -> str:
    backend = DATABASE_BACKEND.strip().lower()
    if backend not in {"sqlite", "postgres", "postgresql"}:
        raise ValueError("DATABASE_BACKEND must be sqlite or postgres")
    return "postgres" if backend == "postgresql" else backend


def is_postgres_backend() -> bool:
    return database_backend() == "postgres"


def split_sql_script(script: str) -> list[str]:
    statements = []
    current = []
    in_single = False
    in_double = False
    index = 0
    while index < len(script):
        char = script[index]
        current.append(char)
        if char == "'" and not in_double:
            in_single = not in_single
        elif char == '"' and not in_single:
            in_double = not in_double
        elif char == ";" and not in_single and not in_double:
            statement = "".join(current).strip().rstrip(";").strip()
            if statement:
                statements.append(statement)
            current = []
        index += 1
    tail = "".join(current).strip()
    if tail:
        statements.append(tail)
    return statements


def translate_postgres_sql(sql: str) -> str:
    translated = sql
    stripped = translated.lstrip()
    if stripped.upper().startswith("INSERT OR IGNORE INTO "):
        leading = translated[: len(translated) - len(stripped)]
        translated = leading + "INSERT INTO " + stripped[len("INSERT OR IGNORE INTO "):]
        if "ON CONFLICT" not in translated.upper():
            translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    translated = translated.replace("?", "%s")
    return translated


def maybe_add_returning_id(sql: str) -> tuple[str, bool]:
    normalized = re.sub(r"\s+", " ", sql.strip()).upper()
    if " RETURNING " in normalized:
        return sql, False
    insert_tables = (
        "INSERT INTO HARVEST_MESSAGES ",
        "INSERT INTO FIELD_WORK_MESSAGES ",
        "INSERT INTO DAILY_VEGETABLE_MANUAL_ENTRIES ",
        "INSERT INTO USERS ",
    )
    if any(normalized.startswith(prefix) for prefix in insert_tables):
        return sql.rstrip().rstrip(";") + " RETURNING id", True
    return sql, False


class PostgresCursor:
    def __init__(self, cursor: Any, lastrowid: int | None = None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self) -> int:
        return int(getattr(self._cursor, "rowcount", -1))

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> list[Any]:
        return self._cursor.fetchall()


class PostgresConnection:
    def __init__(self) -> None:
        if not DATABASE_URL:
            raise ValueError("DATABASE_URL is required when DATABASE_BACKEND=postgres")
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("PostgreSQL support requires the psycopg package") from exc
        self._conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        self._total_changes = 0

    @property
    def total_changes(self) -> int:
        return self._total_changes

    def execute(self, sql: str, params: Iterable[Any] | None = None) -> PostgresCursor:
        translated = translate_postgres_sql(sql)
        translated, fetch_lastrowid = maybe_add_returning_id(translated)
        cursor = self._conn.execute(translated, tuple(params or ()))
        lastrowid = None
        if fetch_lastrowid:
            row = cursor.fetchone()
            lastrowid = int(row["id"]) if row and row.get("id") is not None else None
        if cursor.rowcount and cursor.rowcount > 0:
            self._total_changes += cursor.rowcount
        return PostgresCursor(cursor, lastrowid)

    def executemany(self, sql: str, params: Iterable[Iterable[Any]]) -> PostgresCursor:
        translated = translate_postgres_sql(sql)
        cursor = self._conn.cursor()
        cursor.executemany(translated, [tuple(item) for item in params])
        if cursor.rowcount and cursor.rowcount > 0:
            self._total_changes += cursor.rowcount
        return PostgresCursor(cursor)

    def executescript(self, script: str) -> None:
        for statement in split_sql_script(script):
            self.execute(statement)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


def connect() -> Any:
    if is_postgres_backend():
        return PostgresConnection()
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def init_postgres_db(conn: Any) -> None:
    conn.execute("SELECT pg_advisory_xact_lock(?)", (POSTGRES_SCHEMA_LOCK_ID,))
    conn.executescript(POSTGRES_SCHEMA)
    conn.execute(
        """
        UPDATE users
        SET display_name = CASE
            WHEN username = 'root' THEN 'admin'
            ELSE username
        END
        WHERE COALESCE(display_name, '') = ''
        """
    )
    conn.commit()


def init_db(conn: Any) -> None:
    if is_postgres_backend():
        global _POSTGRES_SCHEMA_INITIALIZED
        if _POSTGRES_SCHEMA_INITIALIZED:
            return
        with _POSTGRES_SCHEMA_INIT_LOCK:
            if _POSTGRES_SCHEMA_INITIALIZED:
                return
            try:
                init_postgres_db(conn)
            except Exception:
                conn.rollback()
                raise
            _POSTGRES_SCHEMA_INITIALIZED = True
        return
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS app_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sales_date TEXT NOT NULL,
            generated_at TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            is_current INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS sales_imports (
            sales_date TEXT PRIMARY KEY,
            file_name TEXT NOT NULL,
            file_path TEXT NOT NULL,
            imported_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS sales_rows (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sales_date TEXT NOT NULL,
            store_code TEXT NOT NULL,
            store_name TEXT,
            product_code TEXT NOT NULL,
            product_name TEXT,
            sales_qty REAL NOT NULL DEFAULT 0,
            discard_qty REAL NOT NULL DEFAULT 0,
            ending_stock REAL NOT NULL DEFAULT 0
        );

        CREATE INDEX IF NOT EXISTS idx_sales_rows_date ON sales_rows (sales_date);
        CREATE INDEX IF NOT EXISTS idx_sales_rows_store_product ON sales_rows (store_code, product_code);
        CREATE INDEX IF NOT EXISTS idx_sales_rows_store_date_product ON sales_rows (store_code, sales_date, product_code);

        CREATE TABLE IF NOT EXISTS store_notes (
            store_key TEXT PRIMARY KEY,
            note TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS store_routes (
            store_key TEXT PRIMARY KEY,
            route TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS shipment_entries (
            store_key TEXT NOT NULL,
            shipment_date TEXT NOT NULL,
            product_code TEXT NOT NULL,
            quantity REAL NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (store_key, shipment_date, product_code)
        );

        CREATE TABLE IF NOT EXISTS stock_adjustment_entries (
            store_key TEXT NOT NULL,
            shipment_date TEXT NOT NULL,
            product_code TEXT NOT NULL,
            quantity REAL NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (store_key, shipment_date, product_code)
        );

        CREATE TABLE IF NOT EXISTS harvest_entries (
            harvest_date TEXT NOT NULL,
            sheet_name TEXT NOT NULL,
            row_index INTEGER NOT NULL,
            column_letter TEXT NOT NULL,
            product_name TEXT NOT NULL,
            quantity REAL NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (harvest_date, sheet_name, row_index, column_letter)
        );

        CREATE TABLE IF NOT EXISTS harvest_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            harvest_date TEXT NOT NULL,
            message TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_harvest_messages_date
            ON harvest_messages (harvest_date, id);

        CREATE TABLE IF NOT EXISTS field_work_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            work_date TEXT NOT NULL,
            zone_name TEXT NOT NULL DEFAULT '',
            net_house_code TEXT NOT NULL DEFAULT '',
            message TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_field_work_messages_date
            ON field_work_messages (work_date, id);

        CREATE TABLE IF NOT EXISTS field_work_message_photos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            message_id INTEGER NOT NULL,
            file_name TEXT NOT NULL,
            original_name TEXT NOT NULL DEFAULT '',
            content_type TEXT NOT NULL DEFAULT '',
            url_path TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_field_work_message_photos_message
            ON field_work_message_photos (message_id, id);

        CREATE TABLE IF NOT EXISTS field_zones (
            zone_name TEXT PRIMARY KEY,
            sort_order INTEGER NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS field_net_houses (
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            grid_count REAL,
            status TEXT NOT NULL DEFAULT '',
            crop1 TEXT NOT NULL DEFAULT '',
            crop2 TEXT NOT NULL DEFAULT '',
            planted_date TEXT NOT NULL DEFAULT '',
            harvest_date TEXT NOT NULL DEFAULT '',
            note TEXT NOT NULL DEFAULT '',
            source_row INTEGER,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (zone_name, net_house_code),
            FOREIGN KEY (zone_name) REFERENCES field_zones(zone_name) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_field_net_houses_zone
            ON field_net_houses (zone_name, net_house_code);

        CREATE TABLE IF NOT EXISTS field_work_records (
            work_date TEXT NOT NULL,
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            task_key TEXT NOT NULL,
            task_label TEXT NOT NULL,
            fertilizer_bag_count REAL,
            crop_key TEXT NOT NULL DEFAULT '',
            crop_name TEXT NOT NULL DEFAULT '',
            account_name TEXT NOT NULL DEFAULT '',
            updated_at TEXT NOT NULL,
            PRIMARY KEY (work_date, zone_name, net_house_code, task_key)
        );

        CREATE INDEX IF NOT EXISTS idx_field_work_records_selection
            ON field_work_records (work_date, zone_name, net_house_code);

        CREATE TABLE IF NOT EXISTS field_work_record_crops (
            work_date TEXT NOT NULL,
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            task_key TEXT NOT NULL,
            crop_index INTEGER NOT NULL,
            crop_key TEXT NOT NULL DEFAULT '',
            crop_name TEXT NOT NULL DEFAULT '',
            tray_count REAL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (work_date, zone_name, net_house_code, task_key, crop_index)
        );

        CREATE INDEX IF NOT EXISTS idx_field_work_record_crops_selection
            ON field_work_record_crops (work_date, zone_name, net_house_code, task_key);

        CREATE INDEX IF NOT EXISTS idx_field_work_record_crops_crop
            ON field_work_record_crops (crop_key);

        CREATE TABLE IF NOT EXISTS field_work_record_audit_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            work_date TEXT NOT NULL,
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            operation TEXT NOT NULL,
            account_name TEXT NOT NULL DEFAULT '',
            before_json TEXT NOT NULL,
            after_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_selection
            ON field_work_record_audit_logs (work_date, zone_name, net_house_code, id);

        CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_created
            ON field_work_record_audit_logs (created_at, id);

        CREATE TABLE IF NOT EXISTS field_bt_records (
            work_date TEXT NOT NULL,
            area_key TEXT NOT NULL,
            area_label TEXT NOT NULL,
            package_count INTEGER,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (work_date, area_key)
        );

        CREATE INDEX IF NOT EXISTS idx_field_bt_records_date
            ON field_bt_records (work_date, area_key);

        CREATE TABLE IF NOT EXISTS net_house_status_records (
            record_date TEXT NOT NULL,
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            status TEXT NOT NULL,
            crop_name TEXT NOT NULL DEFAULT '',
            planted_date TEXT NOT NULL DEFAULT '',
            harvest_date TEXT NOT NULL DEFAULT '',
            estimated_quantity REAL,
            harvest_quantity REAL,
            lunch_marked INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (record_date, zone_name, net_house_code)
        );

        CREATE INDEX IF NOT EXISTS idx_net_house_status_records_date
            ON net_house_status_records (record_date, zone_name, net_house_code);

        CREATE TABLE IF NOT EXISTS net_house_status_record_crops (
            record_date TEXT NOT NULL,
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            crop_index INTEGER NOT NULL,
            crop_name TEXT NOT NULL DEFAULT '',
            harvest_date TEXT NOT NULL DEFAULT '',
            estimated_quantity REAL,
            harvest_quantity REAL,
            destroyed INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (record_date, zone_name, net_house_code, crop_index),
            FOREIGN KEY (record_date, zone_name, net_house_code)
                REFERENCES net_house_status_records(record_date, zone_name, net_house_code)
                ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_net_house_status_record_crops_selection
            ON net_house_status_record_crops (record_date, zone_name, net_house_code);

        CREATE TABLE IF NOT EXISTS daily_vegetable_manual_entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            harvest_date TEXT NOT NULL,
            crop_name TEXT NOT NULL DEFAULT '',
            net_house_code TEXT NOT NULL DEFAULT '',
            quantity REAL,
            updated_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_daily_vegetable_manual_entries_date
            ON daily_vegetable_manual_entries (harvest_date, id);

        CREATE TABLE IF NOT EXISTS app_settings (
            setting_key TEXT PRIMARY KEY,
            setting_value TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL DEFAULT '',
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_users_role
            ON users (role);

        CREATE TABLE IF NOT EXISTS auth_sessions (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_auth_sessions_user
            ON auth_sessions (user_id);

        CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires
            ON auth_sessions (expires_at);

        DROP TABLE IF EXISTS field_edit_logs;
        """
    )
    conn.execute("DELETE FROM sqlite_sequence WHERE name = 'field_edit_logs'")
    user_columns = {
        row["name"]
        for row in conn.execute("PRAGMA table_info(users)").fetchall()
    }
    if "display_name" not in user_columns:
        conn.execute("ALTER TABLE users ADD COLUMN display_name TEXT NOT NULL DEFAULT ''")
    conn.execute(
        """
        UPDATE users
        SET display_name = CASE
            WHEN username = 'root' THEN 'admin'
            ELSE username
        END
        WHERE COALESCE(display_name, '') = ''
        """
    )
    field_work_columns = {
        row["name"]
        for row in conn.execute("PRAGMA table_info(field_work_records)").fetchall()
    }
    if "fertilizer_bag_count" not in field_work_columns:
        conn.execute("ALTER TABLE field_work_records ADD COLUMN fertilizer_bag_count REAL")
    if "crop_key" not in field_work_columns:
        conn.execute("ALTER TABLE field_work_records ADD COLUMN crop_key TEXT NOT NULL DEFAULT ''")
    if "crop_name" not in field_work_columns:
        conn.execute("ALTER TABLE field_work_records ADD COLUMN crop_name TEXT NOT NULL DEFAULT ''")
    if "account_name" not in field_work_columns:
        conn.execute("ALTER TABLE field_work_records ADD COLUMN account_name TEXT NOT NULL DEFAULT ''")
    field_work_message_columns = {
        row["name"]
        for row in conn.execute("PRAGMA table_info(field_work_messages)").fetchall()
    }
    if "zone_name" not in field_work_message_columns:
        conn.execute("ALTER TABLE field_work_messages ADD COLUMN zone_name TEXT NOT NULL DEFAULT ''")
    if "net_house_code" not in field_work_message_columns:
        conn.execute("ALTER TABLE field_work_messages ADD COLUMN net_house_code TEXT NOT NULL DEFAULT ''")
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_field_work_messages_net_house
            ON field_work_messages (zone_name, net_house_code, work_date, id)
        """
    )
    field_work_crop_columns = {
        row["name"]
        for row in conn.execute("PRAGMA table_info(field_work_record_crops)").fetchall()
    }
    if "tray_count" not in field_work_crop_columns:
        conn.execute("ALTER TABLE field_work_record_crops ADD COLUMN tray_count REAL")
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS field_work_record_audit_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            work_date TEXT NOT NULL,
            zone_name TEXT NOT NULL,
            net_house_code TEXT NOT NULL,
            operation TEXT NOT NULL,
            account_name TEXT NOT NULL DEFAULT '',
            before_json TEXT NOT NULL,
            after_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_selection
            ON field_work_record_audit_logs (work_date, zone_name, net_house_code, id)
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_field_work_record_audit_logs_created
            ON field_work_record_audit_logs (created_at, id)
        """
    )
    net_house_status_columns = {
        row["name"]
        for row in conn.execute("PRAGMA table_info(net_house_status_records)").fetchall()
    }
    if "crop_name" not in net_house_status_columns:
        conn.execute("ALTER TABLE net_house_status_records ADD COLUMN crop_name TEXT NOT NULL DEFAULT ''")
    if "planted_date" not in net_house_status_columns:
        conn.execute("ALTER TABLE net_house_status_records ADD COLUMN planted_date TEXT NOT NULL DEFAULT ''")
    if "harvest_date" not in net_house_status_columns:
        conn.execute("ALTER TABLE net_house_status_records ADD COLUMN harvest_date TEXT NOT NULL DEFAULT ''")
    if "estimated_quantity" not in net_house_status_columns:
        conn.execute("ALTER TABLE net_house_status_records ADD COLUMN estimated_quantity REAL")
    if "harvest_quantity" not in net_house_status_columns:
        conn.execute("ALTER TABLE net_house_status_records ADD COLUMN harvest_quantity REAL")
    if "lunch_marked" not in net_house_status_columns:
        conn.execute("ALTER TABLE net_house_status_records ADD COLUMN lunch_marked INTEGER NOT NULL DEFAULT 0")
    net_house_status_crop_columns = {
        row["name"]
        for row in conn.execute("PRAGMA table_info(net_house_status_record_crops)").fetchall()
    }
    if "destroyed" not in net_house_status_crop_columns:
        conn.execute("ALTER TABLE net_house_status_record_crops ADD COLUMN destroyed INTEGER NOT NULL DEFAULT 0")
    if "harvest_quantity" not in net_house_status_crop_columns:
        conn.execute("ALTER TABLE net_house_status_record_crops ADD COLUMN harvest_quantity REAL")
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS daily_vegetable_manual_entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            harvest_date TEXT NOT NULL,
            crop_name TEXT NOT NULL DEFAULT '',
            net_house_code TEXT NOT NULL DEFAULT '',
            quantity REAL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_daily_vegetable_manual_entries_date
            ON daily_vegetable_manual_entries (harvest_date, id)
        """
    )
    conn.commit()


def set_current_snapshot(conn: sqlite3.Connection, payload: dict[str, Any]) -> None:
    generated_at = str(payload.get("generatedAt") or taipei_now_text())
    sales_date = str(payload.get("salesDate") or "")
    conn.execute("UPDATE app_snapshots SET is_current = 0")
    conn.execute(
        "INSERT INTO app_snapshots (sales_date, generated_at, payload_json, is_current) VALUES (?, ?, ?, 1)",
        (sales_date, generated_at, json.dumps(payload, ensure_ascii=False, separators=(",", ":"))),
    )
    conn.commit()


def get_current_snapshot(conn: sqlite3.Connection) -> dict[str, Any] | None:
    row = conn.execute(
        "SELECT payload_json FROM app_snapshots WHERE is_current = 1 ORDER BY id DESC LIMIT 1"
    ).fetchone()
    if not row:
        return None
    return json.loads(row["payload_json"])


def upsert_sales_import(conn: sqlite3.Connection, sales_date: str, file_name: str, file_path: str) -> None:
    conn.execute(
        """
        INSERT INTO sales_imports (sales_date, file_name, file_path, imported_at)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(sales_date) DO UPDATE SET
            file_name = excluded.file_name,
            file_path = excluded.file_path,
            imported_at = excluded.imported_at
        """,
        (sales_date, file_name, file_path, taipei_now_text()),
    )
    conn.commit()


def replace_sales_rows_for_date(conn: sqlite3.Connection, sales_date: str, rows: list[dict[str, Any]]) -> None:
    conn.execute("DELETE FROM sales_rows WHERE sales_date = ?", (sales_date,))
    conn.executemany(
        """
        INSERT INTO sales_rows (
            sales_date,
            store_code,
            store_name,
            product_code,
            product_name,
            sales_qty,
            discard_qty,
            ending_stock
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                sales_date,
                str(row.get("storeCode") or ""),
                row.get("storeName"),
                str(row.get("productCode") or ""),
                row.get("productName"),
                float(row.get("salesQty") or 0),
                float(row.get("discardQty") or 0),
                float(row.get("endingStock") or 0),
            )
            for row in rows
            if row.get("storeCode") and row.get("productCode")
        ],
    )
    conn.commit()


def delete_sales_data(conn: sqlite3.Connection, start_date: str | None = None, end_date: str | None = None) -> None:
    clauses = []
    params: list[str] = []
    if start_date:
        clauses.append("sales_date >= ?")
        params.append(start_date)
    if end_date:
        clauses.append("sales_date <= ?")
        params.append(end_date)
    where = f" WHERE {' AND '.join(clauses)}" if clauses else ""
    conn.execute(f"DELETE FROM sales_rows{where}", params)
    conn.execute(f"DELETE FROM sales_imports{where}", params)
    conn.commit()


def get_store_notes(conn: sqlite3.Connection) -> dict[str, str]:
    rows = conn.execute("SELECT store_key, note FROM store_notes").fetchall()
    return {row["store_key"]: row["note"] for row in rows}


def save_store_note(conn: sqlite3.Connection, store_key: str, note: str) -> None:
    conn.execute(
        """
        INSERT INTO store_notes (store_key, note, updated_at)
        VALUES (?, ?, ?)
        ON CONFLICT(store_key) DO UPDATE SET
            note = excluded.note,
            updated_at = excluded.updated_at
        """,
        (store_key, note, taipei_now_text()),
    )
    conn.commit()


def get_store_routes(conn: sqlite3.Connection) -> dict[str, str]:
    rows = conn.execute("SELECT store_key, route FROM store_routes").fetchall()
    return {row["store_key"]: row["route"] for row in rows}


def save_store_route(conn: sqlite3.Connection, store_key: str, route: str) -> None:
    conn.execute(
        """
        INSERT INTO store_routes (store_key, route, updated_at)
        VALUES (?, ?, ?)
        ON CONFLICT(store_key) DO UPDATE SET
            route = excluded.route,
            updated_at = excluded.updated_at
        """,
        (store_key, route, taipei_now_text()),
    )
    conn.commit()


def get_shipment_entries(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        "SELECT store_key, shipment_date, product_code, quantity FROM shipment_entries"
    ).fetchall()
    return [
        {
            "storeKey": row["store_key"],
            "shipmentDate": row["shipment_date"],
            "productCode": row["product_code"],
            "quantity": row["quantity"],
        }
        for row in rows
    ]


def replace_shipments_for_date(conn: sqlite3.Connection, store_key: str, shipment_date: str, entries: list[dict[str, Any]]) -> None:
    conn.execute(
        "DELETE FROM shipment_entries WHERE store_key = ? AND shipment_date = ?",
        (store_key, shipment_date),
    )
    timestamp = taipei_now_text()
    conn.executemany(
        """
        INSERT INTO shipment_entries (store_key, shipment_date, product_code, quantity, updated_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        [
            (
                store_key,
                shipment_date,
                str(entry["productCode"]),
                float(entry["quantity"]),
                timestamp,
            )
            for entry in entries
            if float(entry["quantity"])
        ],
    )
    conn.commit()


def get_stock_adjustment_entries(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        "SELECT store_key, shipment_date, product_code, quantity FROM stock_adjustment_entries"
    ).fetchall()
    return [
        {
            "storeKey": row["store_key"],
            "shipmentDate": row["shipment_date"],
            "productCode": row["product_code"],
            "quantity": row["quantity"],
        }
        for row in rows
    ]


def replace_stock_adjustments_for_date(
    conn: sqlite3.Connection,
    store_key: str,
    shipment_date: str,
    entries: list[dict[str, Any]],
) -> None:
    conn.execute(
        "DELETE FROM stock_adjustment_entries WHERE store_key = ? AND shipment_date = ?",
        (store_key, shipment_date),
    )
    timestamp = taipei_now_text()
    conn.executemany(
        """
        INSERT INTO stock_adjustment_entries (store_key, shipment_date, product_code, quantity, updated_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        [
            (
                store_key,
                shipment_date,
                str(entry["productCode"]),
                float(entry["quantity"]),
                timestamp,
            )
            for entry in entries
        ],
    )
    conn.commit()


def get_harvest_entries(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT harvest_date, sheet_name, row_index, column_letter, product_name, quantity
        FROM harvest_entries
        ORDER BY harvest_date, sheet_name, row_index, column_letter
        """
    ).fetchall()
    return [
        {
            "harvestDate": row["harvest_date"],
            "sheetName": row["sheet_name"],
            "rowIndex": row["row_index"],
            "columnLetter": row["column_letter"],
            "productName": row["product_name"],
            "quantity": row["quantity"],
        }
        for row in rows
    ]


def replace_harvest_entries_for_date(
    conn: sqlite3.Connection,
    harvest_date: str,
    sheet_name: str,
    entries: list[dict[str, Any]],
) -> None:
    conn.execute(
        "DELETE FROM harvest_entries WHERE harvest_date = ? AND sheet_name = ?",
        (harvest_date, sheet_name),
    )
    timestamp = taipei_now_text()
    normalized_entries = []
    for entry in entries:
        quantity = float(entry.get("quantity") or 0)
        if not quantity:
            continue
        normalized_entries.append(
            (
                harvest_date,
                sheet_name,
                int(entry["rowIndex"]),
                str(entry["columnLetter"]),
                str(entry.get("productName") or ""),
                quantity,
                timestamp,
            )
        )
    conn.executemany(
        """
        INSERT INTO harvest_entries (
            harvest_date, sheet_name, row_index, column_letter, product_name, quantity, updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        normalized_entries,
    )
    conn.commit()


def harvest_message_payload(row: sqlite3.Row) -> dict[str, Any]:
    return {
        "id": row["id"],
        "harvestDate": row["harvest_date"],
        "message": row["message"],
        "createdAt": row["created_at"],
    }


def get_harvest_messages(conn: sqlite3.Connection, harvest_date: str) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT id, harvest_date, message, created_at
        FROM harvest_messages
        WHERE harvest_date = ?
        ORDER BY id
        """,
        (harvest_date,),
    ).fetchall()
    return [harvest_message_payload(row) for row in rows]


def add_harvest_message(conn: sqlite3.Connection, harvest_date: str, message: str) -> dict[str, Any]:
    created_at = taipei_now_text()
    cursor = conn.execute(
        """
        INSERT INTO harvest_messages (harvest_date, message, created_at)
        VALUES (?, ?, ?)
        """,
        (harvest_date, message, created_at),
    )
    conn.commit()
    row = conn.execute(
        """
        SELECT id, harvest_date, message, created_at
        FROM harvest_messages
        WHERE id = ?
        """,
        (cursor.lastrowid,),
    ).fetchone()
    return harvest_message_payload(row)


def delete_harvest_message(conn: sqlite3.Connection, message_id: int, harvest_date: str) -> bool:
    cursor = conn.execute(
        "DELETE FROM harvest_messages WHERE id = ? AND harvest_date = ?",
        (message_id, harvest_date),
    )
    conn.commit()
    return cursor.rowcount > 0


def field_work_message_photo_payload(row: sqlite3.Row) -> dict[str, Any]:
    return {
        "id": row["id"],
        "urlPath": row["url_path"],
        "originalName": row["original_name"],
        "contentType": row["content_type"],
    }


def get_field_work_message_photos(
    conn: sqlite3.Connection,
    message_ids: list[int],
) -> dict[int, list[dict[str, Any]]]:
    photos_by_message: dict[int, list[dict[str, Any]]] = {message_id: [] for message_id in message_ids}
    if not message_ids:
        return photos_by_message
    for index in range(0, len(message_ids), 900):
        chunk = message_ids[index:index + 900]
        placeholders = ",".join("?" for _ in chunk)
        rows = conn.execute(
            f"""
            SELECT id, message_id, file_name, original_name, content_type, url_path, created_at
            FROM field_work_message_photos
            WHERE message_id IN ({placeholders})
            ORDER BY message_id, id
            """,
            chunk,
        ).fetchall()
        for row in rows:
            photos_by_message.setdefault(row["message_id"], []).append(field_work_message_photo_payload(row))
    return photos_by_message


def get_field_work_message_photo_file_names(conn: sqlite3.Connection, message_id: int) -> list[str]:
    rows = conn.execute(
        """
        SELECT file_name
        FROM field_work_message_photos
        WHERE message_id = ?
        """,
        (message_id,),
    ).fetchall()
    return [str(row["file_name"]) for row in rows]


def field_work_message_payload(
    row: sqlite3.Row,
    photos_by_message: dict[int, list[dict[str, Any]]] | None = None,
) -> dict[str, Any]:
    message_id = row["id"]
    return {
        "id": message_id,
        "workDate": row["work_date"],
        "zoneName": row["zone_name"],
        "netHouseCode": row["net_house_code"],
        "message": row["message"],
        "createdAt": row["created_at"],
        "photos": (photos_by_message or {}).get(message_id, []),
    }


def get_field_work_messages(
    conn: sqlite3.Connection,
    work_date: str | None = None,
    zone_name: str | None = None,
    net_house_code: str | None = None,
) -> list[dict[str, Any]]:
    conditions = []
    params: list[Any] = []
    if work_date:
        conditions.append("work_date = ?")
        params.append(work_date)
    if zone_name is not None:
        conditions.append("zone_name = ?")
        params.append(zone_name)
    if net_house_code is not None:
        conditions.append("net_house_code = ?")
        params.append(net_house_code)
    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    rows = conn.execute(
        f"""
        SELECT id, work_date, zone_name, net_house_code, message, created_at
        FROM field_work_messages
        {where_clause}
        ORDER BY work_date DESC, id DESC
        """,
        params,
    ).fetchall()
    message_ids = [row["id"] for row in rows]
    photos_by_message = get_field_work_message_photos(conn, message_ids)
    return [field_work_message_payload(row, photos_by_message) for row in rows]


def add_field_work_message(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
    message: str,
    photos: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    created_at = taipei_now_text()
    cursor = conn.execute(
        """
        INSERT INTO field_work_messages (work_date, zone_name, net_house_code, message, created_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (work_date, zone_name, net_house_code, message, created_at),
    )
    message_id = int(cursor.lastrowid)
    for photo in photos or []:
        file_name = str(photo.get("fileName") or "").strip()
        url_path = str(photo.get("urlPath") or "").strip()
        if not file_name or not url_path:
            continue
        conn.execute(
            """
            INSERT INTO field_work_message_photos
                (message_id, file_name, original_name, content_type, url_path, created_at)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                message_id,
                file_name,
                str(photo.get("originalName") or "").strip(),
                str(photo.get("contentType") or "").strip(),
                url_path,
                created_at,
            ),
        )
    conn.commit()
    row = conn.execute(
        """
        SELECT id, work_date, zone_name, net_house_code, message, created_at
        FROM field_work_messages
        WHERE id = ?
        """,
        (message_id,),
    ).fetchone()
    photos_by_message = get_field_work_message_photos(conn, [message_id])
    return field_work_message_payload(row, photos_by_message)


def delete_field_work_message(
    conn: sqlite3.Connection,
    message_id: int,
    work_date: str | None = None,
    zone_name: str | None = None,
    net_house_code: str | None = None,
) -> bool:
    conditions = ["id = ?"]
    params: list[Any] = [message_id]
    if work_date:
        conditions.append("work_date = ?")
        params.append(work_date)
    if zone_name is not None:
        conditions.append("zone_name = ?")
        params.append(zone_name)
    if net_house_code is not None:
        conditions.append("net_house_code = ?")
        params.append(net_house_code)
    where_clause = " AND ".join(conditions)
    row = conn.execute(
        f"SELECT id FROM field_work_messages WHERE {where_clause}",
        params,
    ).fetchone()
    if not row:
        return False
    conn.execute(
        "DELETE FROM field_work_message_photos WHERE message_id = ?",
        (message_id,),
    )
    cursor = conn.execute(
        f"DELETE FROM field_work_messages WHERE {where_clause}",
        params,
    )
    conn.commit()
    return cursor.rowcount > 0


def replace_field_net_houses(conn: sqlite3.Connection, zones: list[dict[str, Any]]) -> None:
    timestamp = taipei_now_text()
    conn.execute("DELETE FROM field_net_houses")
    conn.execute("DELETE FROM field_zones")
    for zone_index, zone in enumerate(zones):
        zone_name = str(zone.get("name") or "").strip()
        if not zone_name:
            continue
        sort_order = int(zone.get("sortOrder") if zone.get("sortOrder") is not None else zone_index)
        conn.execute(
            """
            INSERT INTO field_zones (zone_name, sort_order, updated_at)
            VALUES (?, ?, ?)
            """,
            (zone_name, sort_order, timestamp),
        )
        rows = []
        for house in zone.get("netHouses") or []:
            net_house_code = str(house.get("netHouseCode") or "").strip()
            if not net_house_code:
                continue
            grid_count = house.get("gridCount")
            rows.append(
                (
                    zone_name,
                    net_house_code,
                    float(grid_count) if grid_count not in (None, "") else None,
                    str(house.get("status") or ""),
                    str(house.get("crop1") or ""),
                    str(house.get("crop2") or ""),
                    str(house.get("plantedDate") or ""),
                    str(house.get("harvestDate") or ""),
                    str(house.get("note") or ""),
                    int(house["sourceRow"]) if house.get("sourceRow") not in (None, "") else None,
                    timestamp,
                )
            )
        conn.executemany(
            """
            INSERT INTO field_net_houses (
                zone_name,
                net_house_code,
                grid_count,
                status,
                crop1,
                crop2,
                planted_date,
                harvest_date,
                note,
                source_row,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            rows,
        )
    conn.commit()


def get_field_net_house_data(conn: sqlite3.Connection) -> dict[str, Any]:
    zone_rows = conn.execute(
        """
        SELECT zone_name, sort_order
        FROM field_zones
        ORDER BY sort_order, zone_name
        """
    ).fetchall()
    zones = [
        {
            "name": row["zone_name"],
            "sortOrder": row["sort_order"],
            "netHouses": [],
        }
        for row in zone_rows
    ]
    zones_by_name = {zone["name"]: zone for zone in zones}
    rows = conn.execute(
        """
        SELECT
            zone_name,
            net_house_code,
            grid_count,
            status,
            crop1,
            crop2,
            planted_date,
            harvest_date,
            note,
            source_row
        FROM field_net_houses
        ORDER BY zone_name, net_house_code
        """
    ).fetchall()
    for row in rows:
        zone = zones_by_name.get(row["zone_name"])
        if not zone:
            zone = {"name": row["zone_name"], "sortOrder": len(zones), "netHouses": []}
            zones.append(zone)
            zones_by_name[zone["name"]] = zone
        zone["netHouses"].append(
            {
                "netHouseCode": row["net_house_code"],
                "gridCount": row["grid_count"],
                "status": row["status"],
                "crop1": row["crop1"],
                "crop2": row["crop2"],
                "plantedDate": row["planted_date"],
                "harvestDate": row["harvest_date"],
                "note": row["note"],
                "sourceRow": row["source_row"],
            }
        )
    return {"zones": zones}


def get_field_work_records(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT
            work_date,
            zone_name,
            net_house_code,
            task_key,
            task_label,
            fertilizer_bag_count,
            crop_key,
            crop_name,
            account_name
        FROM field_work_records
        ORDER BY work_date, zone_name, net_house_code, task_key
        """
    ).fetchall()
    crop_rows = conn.execute(
        """
        SELECT
            work_date,
            zone_name,
            net_house_code,
            task_key,
            crop_key,
            crop_name,
            tray_count
        FROM field_work_record_crops
        ORDER BY work_date, zone_name, net_house_code, task_key, crop_index
        """
    ).fetchall()
    crop_items_by_record: dict[tuple[str, str, str, str], list[dict[str, Any]]] = {}
    for row in crop_rows:
        key = (row["work_date"], row["zone_name"], row["net_house_code"], row["task_key"])
        crop_items_by_record.setdefault(key, []).append(
            {
                "cropKey": row["crop_key"],
                "cropName": row["crop_name"],
                "trayCount": row["tray_count"],
            }
        )

    records = []
    for row in rows:
        key = (row["work_date"], row["zone_name"], row["net_house_code"], row["task_key"])
        crop_items = crop_items_by_record.get(key, [])
        if not crop_items and (row["crop_key"] or row["crop_name"]):
            crop_items = [{"cropKey": row["crop_key"], "cropName": row["crop_name"], "trayCount": None}]
        records.append(
            {
                "workDate": row["work_date"],
                "zoneName": row["zone_name"],
                "netHouseCode": row["net_house_code"],
                "taskKey": row["task_key"],
                "taskLabel": row["task_label"],
                "fertilizerBagCount": row["fertilizer_bag_count"],
                "cropKey": row["crop_key"],
                "cropName": row["crop_name"],
                "accountName": row["account_name"],
                "cropItems": crop_items,
            }
        )
    return records


def get_field_work_records_for_selection(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT
            work_date,
            zone_name,
            net_house_code,
            task_key,
            task_label,
            fertilizer_bag_count,
            crop_key,
            crop_name,
            account_name
        FROM field_work_records
        WHERE work_date = ? AND zone_name = ? AND net_house_code = ?
        ORDER BY task_key
        """,
        (work_date, zone_name, net_house_code),
    ).fetchall()
    crop_rows = conn.execute(
        """
        SELECT
            work_date,
            zone_name,
            net_house_code,
            task_key,
            crop_key,
            crop_name,
            tray_count
        FROM field_work_record_crops
        WHERE work_date = ? AND zone_name = ? AND net_house_code = ?
        ORDER BY task_key, crop_index
        """,
        (work_date, zone_name, net_house_code),
    ).fetchall()
    crop_items_by_record: dict[tuple[str, str, str, str], list[dict[str, Any]]] = {}
    for row in crop_rows:
        key = (row["work_date"], row["zone_name"], row["net_house_code"], row["task_key"])
        crop_items_by_record.setdefault(key, []).append(
            {
                "cropKey": row["crop_key"],
                "cropName": row["crop_name"],
                "trayCount": row["tray_count"],
            }
        )

    records = []
    for row in rows:
        key = (row["work_date"], row["zone_name"], row["net_house_code"], row["task_key"])
        crop_items = crop_items_by_record.get(key, [])
        if not crop_items and (row["crop_key"] or row["crop_name"]):
            crop_items = [{"cropKey": row["crop_key"], "cropName": row["crop_name"], "trayCount": None}]
        records.append(
            {
                "workDate": row["work_date"],
                "zoneName": row["zone_name"],
                "netHouseCode": row["net_house_code"],
                "taskKey": row["task_key"],
                "taskLabel": row["task_label"],
                "fertilizerBagCount": row["fertilizer_bag_count"],
                "cropKey": row["crop_key"],
                "cropName": row["crop_name"],
                "accountName": row["account_name"],
                "cropItems": crop_items,
            }
        )
    return records


def add_field_work_record_audit_log(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
    operation: str,
    account_name: str,
    before_records: list[dict[str, Any]],
    after_records: list[dict[str, Any]],
) -> bool:
    if before_records == after_records:
        return False
    timestamp = taipei_now_text()
    conn.execute(
        """
        INSERT INTO field_work_record_audit_logs (
            work_date,
            zone_name,
            net_house_code,
            operation,
            account_name,
            before_json,
            after_json,
            created_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            work_date,
            zone_name,
            net_house_code,
            operation,
            str(account_name or "")[:80],
            json.dumps(before_records, ensure_ascii=False, separators=(",", ":")),
            json.dumps(after_records, ensure_ascii=False, separators=(",", ":")),
            timestamp,
        ),
    )
    return True


def has_field_work_record(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
) -> bool:
    row = conn.execute(
        """
        SELECT 1
        FROM field_work_records
        WHERE work_date = ? AND zone_name = ? AND net_house_code = ?
        LIMIT 1
        """,
        (work_date, zone_name, net_house_code),
    ).fetchone()
    return row is not None


def active_net_house_status_on_date(
    conn: sqlite3.Connection,
    record_date: str,
    zone_name: str,
    net_house_code: str,
) -> str:
    rows = conn.execute(
        """
        SELECT
            r.record_date,
            r.status,
            r.crop_name,
            r.planted_date,
            r.harvest_date,
            COUNT(c.crop_name) AS crop_count,
            SUM(
                CASE
                    WHEN c.crop_name IS NOT NULL AND NULLIF(c.harvest_date, '') IS NULL THEN 1
                    ELSE 0
                END
            ) AS blank_crop_harvest_count,
            MAX(NULLIF(c.harvest_date, '')) AS crop_harvest_date
        FROM net_house_status_records r
        LEFT JOIN net_house_status_record_crops c
            ON c.record_date = r.record_date
            AND c.zone_name = r.zone_name
            AND c.net_house_code = r.net_house_code
        WHERE r.zone_name = ?
            AND r.net_house_code = ?
            AND r.record_date <= ?
        GROUP BY r.record_date, r.status, r.crop_name, r.planted_date, r.harvest_date
        ORDER BY r.record_date DESC
        """,
        (zone_name, net_house_code, record_date),
    ).fetchall()
    for row in rows:
        status = str(row["status"] or "")
        if status != "種植":
            return status
        planted_date = str(row["planted_date"] or row["record_date"] or "")
        if planted_date and record_date < planted_date:
            continue
        crop_count = int(row["crop_count"] or 0)
        if crop_count == 0 and not str(row["crop_name"] or "").strip():
            continue
        blank_crop_harvest_count = int(row["blank_crop_harvest_count"] or 0)
        harvest_date = "" if crop_count and blank_crop_harvest_count else str(row["crop_harvest_date"] or row["harvest_date"] or "")
        if harvest_date and record_date >= harvest_date:
            continue
        return status
    return ""


def is_field_work_blocked_by_planting(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
) -> bool:
    if has_field_work_record(conn, work_date, zone_name, net_house_code):
        return False
    return active_net_house_status_on_date(conn, work_date, zone_name, net_house_code) == "種植"


def get_field_bt_records(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT work_date, area_key, area_label, package_count
        FROM field_bt_records
        ORDER BY work_date, area_key
        """
    ).fetchall()
    return [
        {
            "workDate": row["work_date"],
            "areaKey": row["area_key"],
            "areaLabel": row["area_label"],
            "packageCount": row["package_count"],
        }
        for row in rows
    ]


def get_field_bt_area_keys_for_date(conn: sqlite3.Connection, work_date: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT area_key
        FROM field_bt_records
        WHERE work_date = ?
        """,
        (work_date,),
    ).fetchall()
    return [row["area_key"] for row in rows]


def daily_vegetable_manual_entry_payload(row: sqlite3.Row) -> dict[str, Any]:
    return {
        "id": int(row["id"]),
        "harvestDate": row["harvest_date"],
        "cropName": row["crop_name"],
        "netHouseCode": row["net_house_code"],
        "quantity": row["quantity"],
        "updatedAt": row["updated_at"],
    }


def get_daily_vegetable_manual_entries(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT id, harvest_date, crop_name, net_house_code, quantity, updated_at
        FROM daily_vegetable_manual_entries
        ORDER BY harvest_date, id
        """
    ).fetchall()
    return [daily_vegetable_manual_entry_payload(row) for row in rows]


def normalize_daily_vegetable_manual_entry(
    harvest_date: str,
    crop_name: str,
    net_house_code: str,
    quantity: object,
) -> tuple[str, str, str, float]:
    normalized_harvest_date = str(harvest_date or "").strip()
    normalized_crop_name = str(crop_name or "").strip()
    normalized_net_house_code = str(net_house_code or "").strip()
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", normalized_harvest_date):
        raise ValueError("採收日期格式錯誤")
    if not normalized_crop_name:
        raise ValueError("請填寫作物")
    if not normalized_net_house_code:
        raise ValueError("請填寫網室編號或來源")
    quantity_text = str(quantity if quantity is not None else "").strip()
    if not quantity_text:
        raise ValueError("請填寫採收量")
    try:
        normalized_quantity = float(quantity_text)
    except (TypeError, ValueError):
        raise ValueError("採收量必須是數字") from None
    if normalized_quantity < 0:
        raise ValueError("採收量不可小於 0")
    return normalized_harvest_date, normalized_crop_name[:80], normalized_net_house_code[:80], normalized_quantity


def add_daily_vegetable_manual_entry(
    conn: sqlite3.Connection,
    harvest_date: str,
    crop_name: str,
    net_house_code: str,
    quantity: object,
) -> dict[str, Any]:
    normalized_harvest_date, normalized_crop_name, normalized_net_house_code, normalized_quantity = (
        normalize_daily_vegetable_manual_entry(harvest_date, crop_name, net_house_code, quantity)
    )
    timestamp = taipei_now_text()
    cursor = conn.execute(
        """
        INSERT INTO daily_vegetable_manual_entries (
            harvest_date,
            crop_name,
            net_house_code,
            quantity,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?)
        """,
        (normalized_harvest_date, normalized_crop_name, normalized_net_house_code, normalized_quantity, timestamp),
    )
    entry_id = int(cursor.lastrowid)
    conn.commit()
    row = conn.execute(
        """
        SELECT id, harvest_date, crop_name, net_house_code, quantity, updated_at
        FROM daily_vegetable_manual_entries
        WHERE id = ?
        """,
        (entry_id,),
    ).fetchone()
    return daily_vegetable_manual_entry_payload(row)


def update_daily_vegetable_manual_entry(
    conn: sqlite3.Connection,
    entry_id: int,
    harvest_date: str,
    crop_name: str,
    net_house_code: str,
    quantity: object,
) -> dict[str, Any]:
    normalized_harvest_date, normalized_crop_name, normalized_net_house_code, normalized_quantity = (
        normalize_daily_vegetable_manual_entry(harvest_date, crop_name, net_house_code, quantity)
    )
    timestamp = taipei_now_text()
    cursor = conn.execute(
        """
        UPDATE daily_vegetable_manual_entries
        SET harvest_date = ?,
            crop_name = ?,
            net_house_code = ?,
            quantity = ?,
            updated_at = ?
        WHERE id = ?
        """,
        (normalized_harvest_date, normalized_crop_name, normalized_net_house_code, normalized_quantity, timestamp, entry_id),
    )
    if cursor.rowcount < 1:
        raise ValueError("找不到手動菜量資料")
    conn.commit()
    row = conn.execute(
        """
        SELECT id, harvest_date, crop_name, net_house_code, quantity, updated_at
        FROM daily_vegetable_manual_entries
        WHERE id = ?
        """,
        (entry_id,),
    ).fetchone()
    return daily_vegetable_manual_entry_payload(row)


def delete_daily_vegetable_manual_entry(conn: sqlite3.Connection, entry_id: int) -> bool:
    cursor = conn.execute(
        "DELETE FROM daily_vegetable_manual_entries WHERE id = ?",
        (entry_id,),
    )
    conn.commit()
    return cursor.rowcount > 0


def split_crop_names(crop_name: str) -> list[str]:
    return [part.strip() for part in str(crop_name or "").split("、") if part.strip()]


def net_house_status_crop_items(
    conn: sqlite3.Connection,
    record_date: str,
    zone_name: str,
    net_house_code: str,
    fallback_crop_name: str = "",
    fallback_harvest_date: str = "",
    fallback_estimated_quantity: float | None = None,
    fallback_harvest_quantity: float | None = None,
) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT crop_name, harvest_date, estimated_quantity, harvest_quantity, destroyed
        FROM net_house_status_record_crops
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        ORDER BY crop_index
        """,
        (record_date, zone_name, net_house_code),
    ).fetchall()
    crop_items = [
        {
            "cropName": row["crop_name"],
            "harvestDate": row["harvest_date"],
            "estimatedQuantity": 0 if bool(row["destroyed"]) else row["estimated_quantity"],
            "harvestQuantity": 0 if bool(row["destroyed"]) else row["harvest_quantity"],
            "destroyed": bool(row["destroyed"]),
        }
        for row in rows
        if row["crop_name"]
    ]
    if crop_items:
        return crop_items
    return [
        {
            "cropName": crop_name,
            "harvestDate": fallback_harvest_date if index == 0 else "",
            "estimatedQuantity": fallback_estimated_quantity if index == 0 else None,
            "harvestQuantity": fallback_harvest_quantity if index == 0 else None,
            "destroyed": False,
        }
        for index, crop_name in enumerate(split_crop_names(fallback_crop_name))
    ]


def net_house_status_record_payload_from_crop_items(
    row: sqlite3.Row,
    crop_items: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    normalized_crop_items = crop_items or [
        {
            "cropName": crop_name,
            "harvestDate": row["harvest_date"] if index == 0 else "",
            "estimatedQuantity": row["estimated_quantity"] if index == 0 else None,
            "harvestQuantity": row["harvest_quantity"] if index == 0 else None,
            "destroyed": False,
        }
        for index, crop_name in enumerate(split_crop_names(row["crop_name"]))
    ]
    return {
        "recordDate": row["record_date"],
        "zoneName": row["zone_name"],
        "netHouseCode": row["net_house_code"],
        "status": row["status"],
        "cropName": normalized_crop_items[0]["cropName"] if normalized_crop_items else row["crop_name"],
        "plantedDate": row["planted_date"],
        "harvestDate": normalized_crop_items[0]["harvestDate"] if normalized_crop_items else row["harvest_date"],
        "estimatedQuantity": normalized_crop_items[0]["estimatedQuantity"] if normalized_crop_items else row["estimated_quantity"],
        "harvestQuantity": normalized_crop_items[0]["harvestQuantity"] if normalized_crop_items else row["harvest_quantity"],
        "destroyed": bool(normalized_crop_items[0].get("destroyed")) if normalized_crop_items else False,
        "lunchMarked": bool(row["lunch_marked"]),
        "cropItems": normalized_crop_items,
    }


def net_house_status_record_payload(conn: sqlite3.Connection, row: sqlite3.Row) -> dict[str, Any]:
    crop_items = net_house_status_crop_items(
        conn,
        row["record_date"],
        row["zone_name"],
        row["net_house_code"],
        row["crop_name"],
        row["harvest_date"],
        row["estimated_quantity"],
        row["harvest_quantity"],
    )
    return net_house_status_record_payload_from_crop_items(row, crop_items)


def get_net_house_status_records(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            lunch_marked
        FROM net_house_status_records
        ORDER BY record_date, zone_name, net_house_code
        """
    ).fetchall()
    crop_rows = conn.execute(
        """
        SELECT
            record_date,
            zone_name,
            net_house_code,
            crop_name,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            destroyed
        FROM net_house_status_record_crops
        ORDER BY record_date, zone_name, net_house_code, crop_index
        """
    ).fetchall()
    crop_items_by_record: dict[tuple[str, str, str], list[dict[str, Any]]] = {}
    for row in crop_rows:
        key = (row["record_date"], row["zone_name"], row["net_house_code"])
        crop_items_by_record.setdefault(key, []).append(
            {
                "cropName": row["crop_name"],
                "harvestDate": row["harvest_date"],
                "estimatedQuantity": 0 if bool(row["destroyed"]) else row["estimated_quantity"],
                "harvestQuantity": 0 if bool(row["destroyed"]) else row["harvest_quantity"],
                "destroyed": bool(row["destroyed"]),
            }
        )
    return [
        net_house_status_record_payload_from_crop_items(
            row,
            crop_items_by_record.get((row["record_date"], row["zone_name"], row["net_house_code"])),
        )
        for row in rows
    ]


def normalize_net_house_status_crop_items(
    crop_items: list[dict[str, Any]] | None,
    crop_name: str = "",
    harvest_date: str = "",
    estimated_quantity: float | None = None,
    harvest_quantity: float | None = None,
) -> list[dict[str, Any]]:
    normalized: list[dict[str, Any]] = []
    source_items = crop_items if isinstance(crop_items, list) else []
    for item in source_items:
        if not isinstance(item, dict):
            continue
        item_crop_name = str(item.get("cropName") or "").strip()
        if not item_crop_name:
            continue
        item_destroyed = bool(item.get("destroyed"))
        normalized.append(
            {
                "cropName": item_crop_name,
                "harvestDate": str(item.get("harvestDate") or "").strip(),
                "estimatedQuantity": 0 if item_destroyed else item.get("estimatedQuantity"),
                "harvestQuantity": 0 if item_destroyed else item.get("harvestQuantity"),
                "destroyed": item_destroyed,
            }
        )
    if normalized:
        return normalized
    return [
        {
            "cropName": item_crop_name,
            "harvestDate": harvest_date if index == 0 else "",
            "estimatedQuantity": estimated_quantity if index == 0 else None,
            "harvestQuantity": harvest_quantity if index == 0 else None,
            "destroyed": False,
        }
        for index, item_crop_name in enumerate(split_crop_names(crop_name))
    ]


def validate_net_house_status_harvest_dates(
    record_date: str,
    planted_date: str = "",
    harvest_date: str = "",
    crop_items: list[dict[str, Any]] | None = None,
) -> None:
    effective_planted_date = str(planted_date or record_date or "").strip()
    if not effective_planted_date:
        return
    harvest_dates = [str(harvest_date or "").strip()]
    if isinstance(crop_items, list):
        harvest_dates.extend(
            str(item.get("harvestDate") or "").strip()
            for item in crop_items
            if isinstance(item, dict)
        )
    if any(item_harvest_date and item_harvest_date < effective_planted_date for item_harvest_date in harvest_dates):
        raise ValueError("採收日期不可早於種植日期，可與種植日期同一天")


def net_house_status_planting_end_date(record: dict[str, Any]) -> str:
    crop_items = record.get("cropItems")
    if isinstance(crop_items, list) and crop_items:
        harvest_dates = [
            str(item.get("harvestDate") or "").strip()
            for item in crop_items
            if isinstance(item, dict) and str(item.get("harvestDate") or "").strip()
        ]
        if len(harvest_dates) < len(crop_items):
            return ""
        return max(harvest_dates) if harvest_dates else ""
    return str(record.get("harvestDate") or "").strip()


def is_net_house_status_active_on_date(record: dict[str, Any], selected_date: str) -> bool:
    if record.get("status") != "種植":
        return True
    planted_date = str(record.get("plantedDate") or record.get("recordDate") or "").strip()
    if planted_date and selected_date < planted_date:
        return False
    harvest_date = net_house_status_planting_end_date(record)
    if harvest_date and selected_date > harvest_date:
        return False
    return True


def get_net_house_status_record(
    conn: sqlite3.Connection,
    record_date: str,
    zone_name: str,
    net_house_code: str,
) -> dict[str, Any] | None:
    row = conn.execute(
        """
        SELECT
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            lunch_marked
        FROM net_house_status_records
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (record_date, zone_name, net_house_code),
    ).fetchone()
    return net_house_status_record_payload(conn, row) if row else None


def latest_active_planting_status_before_date(
    conn: sqlite3.Connection,
    record_date: str,
    zone_name: str,
    net_house_code: str,
) -> dict[str, Any] | None:
    rows = conn.execute(
        """
        SELECT
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            lunch_marked
        FROM net_house_status_records
        WHERE zone_name = ?
            AND net_house_code = ?
            AND record_date < ?
            AND status = '種植'
        ORDER BY record_date DESC
        """,
        (zone_name, net_house_code, record_date),
    ).fetchall()
    for row in rows:
        record = net_house_status_record_payload(conn, row)
        if is_net_house_status_active_on_date(record, record_date):
            return record
    return None


def save_net_house_status_record(
    conn: sqlite3.Connection,
    record_date: str,
    zone_name: str,
    net_house_code: str,
    status: str,
    crop_name: str = "",
    planted_date: str = "",
    harvest_date: str = "",
    estimated_quantity: float | None = None,
    harvest_quantity: float | None = None,
    crop_items: list[dict[str, Any]] | None = None,
    lunch_marked: bool = False,
) -> dict[str, Any] | None:
    timestamp = taipei_now_text()
    existing_record = get_net_house_status_record(conn, record_date, zone_name, net_house_code)
    normalized_crop_items = normalize_net_house_status_crop_items(
        crop_items,
        crop_name,
        harvest_date,
        estimated_quantity,
        harvest_quantity,
    )
    if not normalized_crop_items:
        restore_record = existing_record or latest_active_planting_status_before_date(
            conn,
            record_date,
            zone_name,
            net_house_code,
        )
        if restore_record:
            restored_items = restore_record.get("cropItems")
            if isinstance(restored_items, list):
                normalized_crop_items = [
                    {
                        "cropName": str(item.get("cropName") or "").strip(),
                        "harvestDate": str(item.get("harvestDate") or "").strip(),
                        "estimatedQuantity": 0 if bool(item.get("destroyed")) else item.get("estimatedQuantity"),
                        "harvestQuantity": 0 if bool(item.get("destroyed")) else item.get("harvestQuantity"),
                        "destroyed": bool(item.get("destroyed")),
                    }
                    for item in restored_items
                    if isinstance(item, dict) and str(item.get("cropName") or "").strip()
                ]
            planted_date = planted_date or str(restore_record.get("plantedDate") or restore_record.get("recordDate") or "")
    if status == "種植":
        validate_net_house_status_harvest_dates(record_date, planted_date, harvest_date, normalized_crop_items)
    first_crop = normalized_crop_items[0] if normalized_crop_items else {}
    conn.execute(
        """
        INSERT INTO net_house_status_records (
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            lunch_marked,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(record_date, zone_name, net_house_code)
        DO UPDATE SET
            status = excluded.status,
            crop_name = excluded.crop_name,
            planted_date = excluded.planted_date,
            harvest_date = excluded.harvest_date,
            estimated_quantity = excluded.estimated_quantity,
            harvest_quantity = excluded.harvest_quantity,
            lunch_marked = excluded.lunch_marked,
            updated_at = excluded.updated_at
        """,
        (
            record_date,
            zone_name,
            net_house_code,
            status,
            str(first_crop.get("cropName") or ""),
            planted_date,
            str(first_crop.get("harvestDate") or ""),
            first_crop.get("estimatedQuantity"),
            first_crop.get("harvestQuantity"),
            1 if lunch_marked else 0,
            timestamp,
        ),
    )
    conn.execute(
        """
        DELETE FROM net_house_status_record_crops
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (record_date, zone_name, net_house_code),
    )
    conn.executemany(
        """
        INSERT INTO net_house_status_record_crops (
            record_date,
            zone_name,
            net_house_code,
            crop_index,
            crop_name,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            destroyed,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                record_date,
                zone_name,
                net_house_code,
                index,
                item["cropName"],
                str(item.get("harvestDate") or ""),
                0 if bool(item.get("destroyed")) else item.get("estimatedQuantity"),
                0 if bool(item.get("destroyed")) else item.get("harvestQuantity"),
                1 if bool(item.get("destroyed")) else 0,
                timestamp,
            )
            for index, item in enumerate(normalized_crop_items, start=1)
        ],
    )
    conn.commit()
    row = conn.execute(
        """
        SELECT
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            lunch_marked
        FROM net_house_status_records
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (record_date, zone_name, net_house_code),
    ).fetchone()
    return net_house_status_record_payload(conn, row) if row else None


def crop_items_from_field_work_tasks(tasks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    crop_items: list[dict[str, Any]] = []
    for task in tasks:
        if task.get("taskKey") not in {"directSow", "seedlingTransplant"}:
            continue
        raw_items = task.get("cropItems")
        if isinstance(raw_items, list):
            for item in raw_items:
                if not isinstance(item, dict):
                    continue
                crop_name = str(item.get("cropName") or "").strip()
                if crop_name and not any(existing["cropName"] == crop_name for existing in crop_items):
                    crop_items.append({
                        "cropName": crop_name,
                        "harvestDate": "",
                        "estimatedQuantity": None,
                        "harvestQuantity": None,
                        "destroyed": False,
                    })
        crop_name = str(task.get("cropName") or "").strip()
        if crop_name and not any(existing["cropName"] == crop_name for existing in crop_items):
            crop_items.append({
                "cropName": crop_name,
                "harvestDate": "",
                "estimatedQuantity": None,
                "harvestQuantity": None,
                "destroyed": False,
            })
    return crop_items


def sync_net_house_status_from_field_work(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
    tasks: list[dict[str, Any]],
) -> dict[str, Any] | None:
    crop_items = crop_items_from_field_work_tasks(tasks)
    if not crop_items:
        conn.execute(
            """
            DELETE FROM net_house_status_record_crops
            WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
            """,
            (work_date, zone_name, net_house_code),
        )
        conn.execute(
            """
            DELETE FROM net_house_status_records
            WHERE record_date = ?
                AND zone_name = ?
                AND net_house_code = ?
                AND status = '種植'
                AND planted_date = ?
            """,
            (work_date, zone_name, net_house_code, work_date),
        )
        conn.commit()
        return None

    timestamp = taipei_now_text()
    existing_crop_rows = conn.execute(
        """
        SELECT crop_name, harvest_date, estimated_quantity, harvest_quantity, destroyed
        FROM net_house_status_record_crops
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        ORDER BY crop_index
        """,
        (work_date, zone_name, net_house_code),
    ).fetchall()
    existing_by_crop_name = {
        row["crop_name"]: {
            "harvestDate": row["harvest_date"],
            "estimatedQuantity": 0 if bool(row["destroyed"]) else row["estimated_quantity"],
            "harvestQuantity": 0 if bool(row["destroyed"]) else row["harvest_quantity"],
            "destroyed": bool(row["destroyed"]),
        }
        for row in existing_crop_rows
    }
    legacy_row = conn.execute(
        """
        SELECT harvest_date, estimated_quantity, harvest_quantity
        FROM net_house_status_records
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (work_date, zone_name, net_house_code),
    ).fetchone()
    for index, item in enumerate(crop_items):
        existing = existing_by_crop_name.get(item["cropName"])
        if existing:
            item["harvestDate"] = existing["harvestDate"]
            item["estimatedQuantity"] = existing["estimatedQuantity"]
            item["harvestQuantity"] = existing["harvestQuantity"]
            item["destroyed"] = existing["destroyed"]
        elif index == 0 and legacy_row:
            item["harvestDate"] = legacy_row["harvest_date"]
            item["estimatedQuantity"] = legacy_row["estimated_quantity"]
            item["harvestQuantity"] = legacy_row["harvest_quantity"]
            item["destroyed"] = False

    conn.execute(
        """
        INSERT INTO net_house_status_records (
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            updated_at
        )
        VALUES (?, ?, ?, '種植', ?, ?, '', NULL, NULL, ?)
        ON CONFLICT(record_date, zone_name, net_house_code)
        DO UPDATE SET
            status = '種植',
            crop_name = excluded.crop_name,
            planted_date = excluded.planted_date,
            updated_at = excluded.updated_at
        """,
        (work_date, zone_name, net_house_code, crop_items[0]["cropName"], work_date, timestamp),
    )
    conn.execute(
        """
        DELETE FROM net_house_status_record_crops
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (work_date, zone_name, net_house_code),
    )
    conn.executemany(
        """
        INSERT INTO net_house_status_record_crops (
            record_date,
            zone_name,
            net_house_code,
            crop_index,
            crop_name,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            destroyed,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                work_date,
                zone_name,
                net_house_code,
                index,
                item["cropName"],
                str(item.get("harvestDate") or ""),
                0 if bool(item.get("destroyed")) else item.get("estimatedQuantity"),
                0 if bool(item.get("destroyed")) else item.get("harvestQuantity"),
                1 if bool(item.get("destroyed")) else 0,
                timestamp,
            )
            for index, item in enumerate(crop_items, start=1)
        ],
    )
    conn.commit()
    row = conn.execute(
        """
        SELECT
            record_date,
            zone_name,
            net_house_code,
            status,
            crop_name,
            planted_date,
            harvest_date,
            estimated_quantity,
            harvest_quantity,
            lunch_marked
        FROM net_house_status_records
        WHERE record_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (work_date, zone_name, net_house_code),
    ).fetchone()
    if not row:
        return None
    return net_house_status_record_payload(conn, row)


def replace_field_bt_records(
    conn: sqlite3.Connection,
    work_date: str,
    records: list[dict[str, Any]],
) -> None:
    conn.execute("DELETE FROM field_bt_records WHERE work_date = ?", (work_date,))
    timestamp = taipei_now_text()
    rows = []
    for record in records:
        area_key = str(record.get("areaKey") or "")
        if not area_key:
            continue
        package_count = record.get("packageCount")
        rows.append(
            (
                work_date,
                area_key,
                str(record.get("areaLabel") or ""),
                int(package_count) if package_count not in (None, "") else None,
                timestamp,
            )
        )
    conn.executemany(
        """
        INSERT INTO field_bt_records (
            work_date,
            area_key,
            area_label,
            package_count,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?)
        """,
        rows,
    )
    conn.commit()


def replace_field_work_records(
    conn: sqlite3.Connection,
    work_date: str,
    zone_name: str,
    net_house_code: str,
    tasks: list[dict[str, Any]],
    account_name: str = "",
) -> bool:
    before_records = get_field_work_records_for_selection(conn, work_date, zone_name, net_house_code)
    conn.execute(
        """
        DELETE FROM field_work_record_crops
        WHERE work_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (work_date, zone_name, net_house_code),
    )
    conn.execute(
        """
        DELETE FROM field_work_records
        WHERE work_date = ? AND zone_name = ? AND net_house_code = ?
        """,
        (work_date, zone_name, net_house_code),
    )
    timestamp = taipei_now_text()
    rows = []
    crop_rows = []
    for task in tasks:
        task_key = str(task.get("taskKey") or "")
        if not task_key:
            continue
        crop_items = []
        raw_crop_items = task.get("cropItems")
        if isinstance(raw_crop_items, list):
            for raw_item in raw_crop_items:
                if not isinstance(raw_item, dict):
                    continue
                crop_key = str(raw_item.get("cropKey") or "")
                crop_name = str(raw_item.get("cropName") or "")
                tray_count = raw_item.get("trayCount")
                if crop_key or crop_name:
                    crop_items.append({"cropKey": crop_key, "cropName": crop_name, "trayCount": tray_count})
        if not crop_items and (task.get("cropKey") or task.get("cropName")):
            crop_items.append(
                {
                    "cropKey": str(task.get("cropKey") or ""),
                    "cropName": str(task.get("cropName") or ""),
                    "trayCount": None,
                }
            )
        first_crop = crop_items[0] if crop_items else {"cropKey": "", "cropName": ""}
        fertilizer_bag_count = task.get("fertilizerBagCount")
        rows.append(
            (
                work_date,
                zone_name,
                net_house_code,
                task_key,
                str(task.get("taskLabel") or ""),
                float(fertilizer_bag_count) if fertilizer_bag_count not in (None, "") else None,
                str(first_crop.get("cropKey") or ""),
                str(first_crop.get("cropName") or ""),
                str(account_name or "")[:80],
                timestamp,
            )
        )
        for index, crop_item in enumerate(crop_items, start=1):
            crop_rows.append(
                (
                    work_date,
                    zone_name,
                    net_house_code,
                    task_key,
                    index,
                    str(crop_item.get("cropKey") or ""),
                    str(crop_item.get("cropName") or ""),
                    float(crop_item.get("trayCount")) if crop_item.get("trayCount") not in (None, "") else None,
                    timestamp,
                )
            )
    conn.executemany(
        """
        INSERT INTO field_work_records (
            work_date,
            zone_name,
            net_house_code,
            task_key,
            task_label,
            fertilizer_bag_count,
            crop_key,
            crop_name,
            account_name,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        rows,
    )
    conn.executemany(
        """
        INSERT INTO field_work_record_crops (
            work_date,
            zone_name,
            net_house_code,
            task_key,
            crop_index,
            crop_key,
            crop_name,
            tray_count,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        crop_rows,
    )
    after_records = get_field_work_records_for_selection(conn, work_date, zone_name, net_house_code)
    audit_logged = add_field_work_record_audit_log(
        conn,
        work_date,
        zone_name,
        net_house_code,
        "replace",
        account_name,
        before_records,
        after_records,
    )
    conn.commit()
    return audit_logged


def ensure_field_work_task_for_zones(
    conn: sqlite3.Connection,
    work_date: str,
    zone_names: list[str],
    task_key: str,
    task_label: str,
    account_name: str = "",
) -> int:
    normalized_zone_names = []
    seen = set()
    for zone_name in zone_names:
        zone_name = str(zone_name or "").strip()
        if zone_name and zone_name not in seen:
            seen.add(zone_name)
            normalized_zone_names.append(zone_name)
    if not normalized_zone_names:
        return 0

    timestamp = taipei_now_text()
    before_changes = conn.total_changes
    for zone_name in normalized_zone_names:
        conn.execute(
            """
            INSERT OR IGNORE INTO field_work_records (
                work_date,
                zone_name,
                net_house_code,
                task_key,
                task_label,
                fertilizer_bag_count,
                crop_key,
                crop_name,
                account_name,
                updated_at
            )
            SELECT
                ?,
                zone_name,
                net_house_code,
                ?,
                ?,
                NULL,
                '',
                '',
                ?,
                ?
            FROM field_net_houses
            WHERE zone_name = ?
            """,
            (work_date, task_key, task_label, str(account_name or "")[:80], timestamp, zone_name),
        )
    conn.commit()
    return conn.total_changes - before_changes


def delete_field_work_task_for_zones(
    conn: sqlite3.Connection,
    work_date: str,
    zone_names: list[str],
    task_key: str,
) -> int:
    normalized_zone_names = []
    seen = set()
    for zone_name in zone_names:
        zone_name = str(zone_name or "").strip()
        if zone_name and zone_name not in seen:
            seen.add(zone_name)
            normalized_zone_names.append(zone_name)
    if not normalized_zone_names:
        return 0

    before_changes = conn.total_changes
    for zone_name in normalized_zone_names:
        conn.execute(
            """
            DELETE FROM field_work_record_crops
            WHERE work_date = ? AND zone_name = ? AND task_key = ?
            """,
            (work_date, zone_name, task_key),
        )
        conn.execute(
            """
            DELETE FROM field_work_records
            WHERE work_date = ? AND zone_name = ? AND task_key = ?
            """,
            (work_date, zone_name, task_key),
        )
    conn.commit()
    return conn.total_changes - before_changes


def get_setting(conn: sqlite3.Connection, setting_key: str) -> Any | None:
    row = conn.execute(
        "SELECT setting_value FROM app_settings WHERE setting_key = ?",
        (setting_key,),
    ).fetchone()
    if not row:
        return None
    return json.loads(row["setting_value"])


def save_setting(conn: sqlite3.Connection, setting_key: str, value: Any) -> None:
    conn.execute(
        """
        INSERT INTO app_settings (setting_key, setting_value, updated_at)
        VALUES (?, ?, ?)
        ON CONFLICT(setting_key) DO UPDATE SET
            setting_value = excluded.setting_value,
            updated_at = excluded.updated_at
        """,
        (
            setting_key,
            json.dumps(value, ensure_ascii=False, separators=(",", ":")),
            taipei_now_text(),
        ),
    )
    conn.commit()
